"""Generated by ``tools/generate_icons.py`` — do not edit by hand.

The built-in icon vocabulary ships as plain data. This module is part
of the framework runtime, so :mod:`pydrud.icons` answers correctly in an
application, a test, or the analyzer.

``tests/test_icons.py`` pins this data to the generated renderer, so the two
can never drift.
"""

from __future__ import annotations

#: Every icon the renderer can draw, as one whitespace-delimited string.
_NAMES = """\
add add_circle agenda alarm android apps archive arrow_down arrow_up attach
back bank battery battery_charging bluetooth book bookmark bookmark_border
brightness brush bug build calendar call call_end camera cancel cart chart
chat check check_circle chevron_left chevron_right circle clock close cloud
cloud_download cloud_upload code coffee comment copy crop cut dark_mode
dashboard database delete desktop diamond download drag edit email emoji
error event expand_less expand_more favorite favorite_border file filter
fingerprint fire flag folder folder_open food forward fullscreen
fullscreen_exit gallery gift globe grid group headphones help history home
image inbox info key layers leaf light_mode lightbulb link list location
lock lock_open login logout map menu mic mic_off more_horiz more_vert music
navigation notifications notifications_off open_in_new palette paste pause
payment person person_add person_remove phone_android pie_chart play power
print puzzle python qr_code redo refresh remove remove_circle rocket rotate
save school search send settings share shield skip_next skip_previous sort
sparkle square star star_border stop store swap sync tag terminal thumb_down
thumb_up timer translate trending_down trending_up triangle truck tune undo
upload verified video visibility visibility_off volume volume_off wallet
warning watch water wifi wifi_off work zoom_in zoom_out
""".split()

#: Alias -> canonical path, as two parallel strings.
_ALIAS_NAMES = """\
account account_tree add_circle_outline alert analytics animation api
arrow_back arrow_circle_down arrow_circle_up arrow_down arrow_drop_down
arrow_drop_up arrow_forward arrow_left arrow_right arrow_up astrophysics
attachment backspace bar_chart bell bin block bolt calendar_today canvas
cast check_circle_outline circle clear clock_outline cloud_done cog compass
content_copy content_cut content_paste controller credit_card danger date
delete_outline diamond directions_car doc document done done_all dots
edit_note emoji_events error_outline exit eye eye_off favorite_outline
file_download file_upload filter_alt first_page flash flash_on flight
fullscreen_exit gamepad games gear graph heart heart_border heart_broken
home_work hotel hourglass_bottom idea joystick keyboard_arrow_down
keyboard_arrow_left keyboard_arrow_right keyboard_arrow_up language
last_page library_books location_pin lock_outline magic magnify mail message
minus money moon more_time mute night note_add notification_important
notifications_active ok open_in_full pause_circle pencil people
person_outline phone photo photos picture picture_as_pdf pin place
play_arrow play_circle playlist_add plus print_outline profile publish
question queue_music record remove_red_eye repeat repeat_one replay
restart_alt restaurant rocket_launch save_alt scan schedule screen_rotation
security server shop shopping_bag shopping_cart shuffle sign_in sign_out
sound spark sparkles speed sports_esports square star_outline star_rate
state stats sun support sync_alt task_alt thumb_up_alt tick time today touch
touch_app trash trending_flat triangle trophy upload_file user users
verified_user vibration videocam view_list volume_mute volume_off volume_up
warning_amber work_outline zoom_out_map
""".split()

_ALIAS_TARGETS = """\
person list add_circle warning chart sparkle code back arrow_down arrow_up
expand_more expand_more expand_less forward back forward expand_less rocket
attach back chart notifications delete cancel sparkle calendar palette
fullscreen check_circle circle close clock cloud settings navigation copy
cut paste play payment error calendar delete diamond navigation file file
check check more_vert edit verified error logout visibility visibility_off
favorite_border download upload filter skip_previous sparkle sparkle rocket
fullscreen play play settings chart favorite favorite_border favorite_border
home home timer lightbulb play expand_more chevron_left chevron_right
expand_less translate skip_next book location lock sparkle search email chat
remove payment dark_mode timer volume dark_mode add notifications
notifications check fullscreen pause edit group person call image gallery
image file location location play play list add print person upload help
music stop visibility sync sync refresh undo food rocket save qr_code clock
refresh shield database store cart cart swap login logout volume sparkle
sparkle timer play square star_border star sync chart light_mode help sync
check_circle thumb_up check clock event drag drag delete trending_up
triangle verified upload person group shield notifications video list volume
volume volume warning work fullscreen
""".split()

PATHS: frozenset = frozenset(_NAMES)
ALIASES: dict = dict(zip(_ALIAS_NAMES, _ALIAS_TARGETS))
