"""Widget system for Pydrud."""

from pydrud.widgets.base import Widget, assign_stable_keys, validate_tree_keys
from pydrud.widgets.styling import (
    Style, EdgeInsets, Alignment, FontStyle, Border, BorderSide, BorderRadius,
    LinearGradient, RadialGradient, SweepGradient,
)
from pydrud.widgets.layout import (
    Container, Column, Row, Center, Spacer, Divider,
    Stack, Positioned, SizedBox, Padding, Card, ListView, GridView, PageView,
)
from pydrud.widgets.basic import (
    Text, Button, FilledButton, TonalButton, OutlinedButton, TextButton,
    ElevatedButton, IconButton, TextField, SearchField, EmailField,
    PasswordField, NumberField, PhoneField, UrlField, Image, SvgPicture, Icon, Checkbox,
    Switch, ProgressBar, LinearProgress, Slider, RangeSlider, Dropdown, Radio,
)
from pydrud.widgets.theme import (Colors, Icons, Theme, ColorScheme, Typography,
                                  Spacing, Radius, Elevation, Motion,
                                  TextTheme, ThemeExtension)
from pydrud.widgets.tokens import Tokens
from pydrud.widgets.material import (
    ListTile, ExpansionTile, ExpansionPanel, ExpansionPanelList,
    Chip, AssistChip, FilterChip, InputChip,
    SuggestionChip, Badge, Avatar, Banner, Tooltip,
    Tab, Tabs, TabBar, NavItem, NavigationItem, NavigationDestination,
    BottomNavigationBar, NavigationBar,
    NavigationRail, Drawer,
    SegmentedButton, SearchBar, Rating, CircularProgress, Skeleton,
    RefreshIndicator, Stepper, WebView, VideoPlayer, Chart,
    MenuItem, MenuDivider, PopupMenu, PopupMenuButton, DropdownMenu,
)
from pydrud.widgets.gestures import GestureDetector, InkWell, Dismissible, Draggable
from pydrud.widgets.animation import (
    Animation, AnimatedContainer, AnimatedOpacity, AnimatedScale,
    AnimatedRotation, AnimatedSwitcher, FadeIn, SlideIn, ScaleIn, Hero, animate,
)
from pydrud.widgets.forms import (
    Form, FormField, required, min_length, max_length, email, phone, url,
    numeric, between, pattern, matches, custom,
)
from pydrud.widgets.canvas import Canvas, Paint, Path, radial_point
from pydrud.widgets.advanced import (
    CameraPreview, QRScanner, InfiniteList, MapView, Markdown, Marker,
    NativeView, ReorderableList, RichText, Span,
)
from pydrud.widgets.app_bar import AppBar
from pydrud.widgets.scaffold import Scaffold
from pydrud.widgets.fab import FloatingActionButton
from pydrud.widgets.responsive import (
    AdaptiveLayout, Constraints, LayoutBuilder, ResponsiveBuilder,
    ResponsiveGrid, SafeArea, ShowWhen,
)
from pydrud.widgets.conditional import Hidden, Visible
from pydrud.widgets.presets import (
    ActionChip, Align, AssetImage, BackButton, ButtonBar, Caption,
    CheckboxListTile, ChoiceChip, CircleAvatar, CircleImage, CloseButton,
    ColoredBox, ConstrainedBox, DecoratedBox, EmptyState, ErrorState, Expanded,
    Flexible, Flex, FractionallySizedBox, FittedBox, MetricCard, DataTable,
    Timeline, Carousel,
    FormSection, Gap, Heading, InfoCard, Label, LimitedBox, Link,
    LoadingState, MenuButton, NavigationTile, NetworkImage, Placeholder,
    RadioListTile, SectionHeader, SettingsTile, SingleChildScrollView, StatCard,
    Subtitle, SwitchListTile, Title, VerticalDivider, Wrap,
)

__all__ = [
    "Widget",
    "assign_stable_keys",
    "validate_tree_keys",
    # layout
    "Container",
    "Column",
    "Row",
    "Flex",
    "Center",
    "Spacer",
    "Divider",
    "Stack",
    "Positioned",
    "SizedBox",
    "Padding",
    "Card",
    "ListView",
    "GridView",
    "PageView",
    # basic
    "Text",
    "Button",
    "FilledButton",
    "TonalButton",
    "OutlinedButton",
    "TextButton",
    "ElevatedButton",
    "IconButton",
    "TextField",
    "SearchField",
    "EmailField",
    "PasswordField",
    "NumberField",
    "PhoneField",
    "UrlField",
    "Image",
    "SvgPicture",
    "Icon",
    "Checkbox",
    "Switch",
    "ProgressBar",
    "LinearProgress",
    "Slider",
    "RangeSlider",
    "Dropdown",
    "Radio",
    # structure
    "AppBar",
    "Scaffold",
    "FloatingActionButton",
    # styling
    "Style",
    "EdgeInsets",
    "Alignment",
    "FontStyle",
    "Border",
    "BorderSide",
    "BorderRadius",
    "LinearGradient",
    "RadialGradient",
    "SweepGradient",
    "Colors",
    "Spacing",
    "Radius",
    "Elevation",
    "Motion",
    "Tokens",
    "Icons",
    "Theme",
    "ColorScheme",
    "Typography",
    "TextTheme",
    "ThemeExtension",
    # material
    "ListTile",
    "ExpansionTile",
    "ExpansionPanel",
    "ExpansionPanelList",
    "Chip",
    "AssistChip",
    "FilterChip",
    "InputChip",
    "SuggestionChip",
    "Badge",
    "Avatar",
    "Banner",
    "Tooltip",
    "Tab",
    "Tabs",
    "TabBar",
    "NavItem",
    "NavigationItem",
    "NavigationDestination",
    "BottomNavigationBar",
    "NavigationBar",
    "NavigationRail",
    "Drawer",
    "SegmentedButton",
    "SearchBar",
    "Rating",
    "CircularProgress",
    "Skeleton",
    "RefreshIndicator",
    "Stepper",
    "WebView",
    "VideoPlayer",
    "Chart",
    # menus
    "MenuItem",
    "MenuDivider",
    "PopupMenu",
    "PopupMenuButton",
    "DropdownMenu",
    # gestures
    "GestureDetector",
    "InkWell",
    "Dismissible",
    "Draggable",
    # animation
    "Animation",
    "AnimatedContainer",
    "AnimatedOpacity",
    "AnimatedScale",
    "AnimatedRotation",
    "AnimatedSwitcher",
    "FadeIn",
    "SlideIn",
    "ScaleIn",
    "Hero",
    "animate",
    # forms
    "Form",
    "FormField",
    "required",
    "min_length",
    "max_length",
    "email",
    "phone",
    "url",
    "numeric",
    "between",
    "pattern",
    "matches",
    "custom",
    # v1.3 — painting, hardware, maps, rich text and big lists
    "Canvas",
    "Paint",
    "Path",
    "radial_point",
    "CameraPreview",
    "QRScanner",
    "MapView",
    "Marker",
    "RichText",
    "Span",
    "Markdown",
    "ReorderableList",
    "InfiniteList",
    "NativeView",
    # v1.5 — responsive layout
    "ResponsiveBuilder",
    "LayoutBuilder",
    "Constraints",
    "AdaptiveLayout",
    "ResponsiveGrid",
    "ShowWhen",
    "SafeArea",
    # conditional rendering
    "Visible",
    "Hidden",
    # Flutter-style presets and common compositions
    "Expanded",
    "Flexible",
    "FractionallySizedBox",
    "FittedBox",
    "MetricCard",
    "DataTable",
    "Timeline",
    "Carousel",
    "Align",
    "ColoredBox",
    "DecoratedBox",
    "ConstrainedBox",
    "LimitedBox",
    "Gap",
    "VerticalDivider",
    "SingleChildScrollView",
    "Wrap",
    "ButtonBar",
    "Heading",
    "Title",
    "Subtitle",
    "Label",
    "Caption",
    "Link",
    "NetworkImage",
    "AssetImage",
    "CircleImage",
    "Placeholder",
    "SwitchListTile",
    "CheckboxListTile",
    "RadioListTile",
    "ActionChip",
    "ChoiceChip",
    "CircleAvatar",
    "BackButton",
    "CloseButton",
    "MenuButton",
    "SectionHeader",
    "EmptyState",
    "ErrorState",
    "LoadingState",
    "InfoCard",
    "StatCard",
    "SettingsTile",
    "NavigationTile",
    "FormSection",
]
