"""
Pydrud — Build native Android apps with Python.

A lightweight, Flutter-inspired framework that converts a declarative
Python widget tree into native Android Views at runtime. No XML layouts,
no Kotlin UI code — just Python.
"""

__version__ = "2.0.3"
__app_name__ = "Pydrud"

from pydrud.runtime.app import App
from pydrud.core.errors import PydrudError, MaxDepthError, FrameTooLargeError
from pydrud.core.state import State, ReactiveDict
from pydrud.core.store import Store, Selector, Computed, ReactiveList
from pydrud.core.events import Event, EventDispatcher
from pydrud.core.results import Result, ResultError
from pydrud.core.elements import Element, ElementTree
from pydrud.core.subscriptions import Subscription
from pydrud.core.tasks import TaskRunner, Timer, debounce, throttle, job
from pydrud.core.responsive import (Breakpoints, MediaQuery, Responsive,
                                    ScreenInfo)
from pydrud.runtime.navigation import Router, NavigationStack, Route, parse_url
from pydrud.core.controllers import AnimationController, Tween, curve
from pydrud.data import Cache, Database, Field, Migration, Model, Query, cached, column
from pydrud.widgets import (
    Widget,
    Container,
    Column,
    Row,
    Center,
    Spacer,
    Divider,
    Stack,
    Positioned,
    SizedBox,
    Padding,
    Card,
    ListView,
    GridView,
    Text,
    Button,
    FilledButton,
    TonalButton,
    OutlinedButton,
    TextButton,
    ElevatedButton,
    IconButton,
    TextField,
    SearchField,
    EmailField,
    PasswordField,
    NumberField,
    PhoneField,
    UrlField,
    Image,
    SvgPicture,
    Icon,
    Checkbox,
    Switch,
    ProgressBar,
    LinearProgress,
    Slider,
    Dropdown,
    Radio,
    AppBar,
    Scaffold,
    FloatingActionButton,
    Style,
    EdgeInsets,
    Alignment,
    FontStyle,
    Border,
    BorderSide,
    BorderRadius,
    LinearGradient,
    RadialGradient,
    SweepGradient,
    Colors,
    Icons,
    Theme,
    Spacing,
    Radius,
    Elevation,
    Motion,
    Tokens,
    ColorScheme,
    Typography,
    ListTile,
    ExpansionTile,
    Chip,
    AssistChip,
    FilterChip,
    InputChip,
    SuggestionChip,
    Badge,
    Avatar,
    Banner,
    Tooltip,
    Tab,
    Tabs,
    NavItem,
    NavigationItem,
    NavigationDestination,
    BottomNavigationBar,
    NavigationBar,
    TabBar,
    AdaptiveLayout,
    ResponsiveBuilder,
    ResponsiveGrid,
    SafeArea,
    ShowWhen,
    Visible,
    Hidden,
    NavigationRail,
    Drawer,
    SegmentedButton,
    SearchBar,
    Rating,
    CircularProgress,
    Skeleton,
    RefreshIndicator,
    Stepper,
    WebView,
    VideoPlayer,
    Chart,
    GestureDetector,
    InkWell,
    Dismissible,
    Draggable,
    Animation,
    AnimatedContainer,
    AnimatedOpacity,
    AnimatedScale,
    AnimatedRotation,
    AnimatedSwitcher,
    FadeIn,
    SlideIn,
    ScaleIn,
    Hero,
    animate,
    Form,
    FormField,
    required,
    min_length,
    max_length,
    email,
    phone,
    url,
    numeric,
    between,
    pattern,
    matches,
    custom,
    Canvas, Paint, Path, radial_point,
    CameraPreview, QRScanner, MapView, Marker, RichText, Span, Markdown,
    ReorderableList, InfiniteList,
    Expanded, Flexible, FractionallySizedBox, FittedBox, MetricCard, DataTable,
    Timeline, Align, ColoredBox, DecoratedBox, ConstrainedBox, LimitedBox,
    Gap, VerticalDivider,
    SingleChildScrollView, Wrap, ButtonBar,
    Heading, Title, Subtitle, Label, Caption, Link, NetworkImage, AssetImage,
    CircleImage, Placeholder, SwitchListTile, CheckboxListTile, RadioListTile,
    ActionChip, ChoiceChip, CircleAvatar, BackButton, CloseButton, MenuButton,
    SectionHeader, EmptyState, ErrorState, LoadingState, InfoCard, StatCard,
    SettingsTile, NavigationTile, FormSection,
)

__all__ = [
    "App",
    "PydrudError",
    "MaxDepthError",
    "FrameTooLargeError",
    "Responsive",
    "MediaQuery",
    "Breakpoints",
    "ScreenInfo",
    "Router",
    "NavigationStack",
    "Route",
    "State",
    "ReactiveDict",
    "Store",
    "Selector",
    "Computed",
    "ReactiveList",
    "Event",
    "EventDispatcher",
    "Result",
    "ResultError",
    "Element",
    "ElementTree",
    "Subscription",
    "TaskRunner",
    "Timer",
    "debounce",
    "throttle",
    "job",
    "Widget",
    "Container",
    "Column",
    "Row",
    "Center",
    "Spacer",
    "Divider",
    "Stack",
    "Positioned",
    "SizedBox",
    "Padding",
    "Card",
    "ListView",
    "GridView",
    "Text",
    "Button",
    "FilledButton",
    "TonalButton",
    "OutlinedButton",
    "TextButton",
    "ElevatedButton",
    "IconButton",
    "TextField",
    "SearchField",
    "EmailField",
    "PasswordField",
    "NumberField",
    "PhoneField",
    "UrlField",
    "Image",
    "SvgPicture",
    "Icon",
    "Checkbox",
    "Switch",
    "ProgressBar",
    "LinearProgress",
    "Slider",
    "Dropdown",
    "Radio",
    "AppBar",
    "Scaffold",
    "FloatingActionButton",
    "Style",
    "EdgeInsets",
    "Alignment",
    "FontStyle",
    "Border",
    "BorderSide",
    "BorderRadius",
    "LinearGradient",
    "RadialGradient",
    "SweepGradient",
    "Colors",
    "Spacing",
    "Radius",
    "Elevation",
    "Motion",
    "Tokens",
    "Icons",
    "Theme",
    "ColorScheme",
    "Typography",
    "ListTile",
    "ExpansionTile",
    "Chip",
    "AssistChip",
    "FilterChip",
    "InputChip",
    "SuggestionChip",
    "Badge",
    "Avatar",
    "Banner",
    "Tooltip",
    "Tab",
    "Tabs",
    "NavItem",
    "NavigationItem",
    "NavigationDestination",
    "BottomNavigationBar",
    "NavigationBar",
    "TabBar",
    "AdaptiveLayout",
    "ResponsiveBuilder",
    "ResponsiveGrid",
    "SafeArea",
    "ShowWhen",
    "Visible",
    "Hidden",
    "NavigationRail",
    "Drawer",
    "SegmentedButton",
    "SearchBar",
    "Rating",
    "CircularProgress",
    "Skeleton",
    "RefreshIndicator",
    "Stepper",
    "WebView",
    "VideoPlayer",
    "Chart",
    "GestureDetector",
    "InkWell",
    "Dismissible",
    "Draggable",
    "Animation",
    "AnimatedContainer",
    "AnimatedOpacity",
    "AnimatedScale",
    "AnimatedRotation",
    "AnimatedSwitcher",
    "FadeIn",
    "SlideIn",
    "ScaleIn",
    "Hero",
    "animate",
    "Form",
    "FormField",
    "required",
    "min_length",
    "max_length",
    "email",
    "phone",
    "url",
    "numeric",
    "between",
    "pattern",
    "matches",
    "custom",
    # v1.3 — painting, hardware, maps, rich text and big lists
    "Canvas",
    "Paint",
    "Path",
    "radial_point",
    "CameraPreview",
    "QRScanner",
    "MapView",
    "Marker",
    "RichText",
    "Span",
    "Markdown",
    "ReorderableList",
    "InfiniteList",
    # Flutter-style presets and common compositions
    "Expanded",
    "Flexible",
    "FractionallySizedBox",
    "FittedBox",
    "MetricCard",
    "DataTable",
    "Timeline",
    "Align",
    "ColoredBox",
    "DecoratedBox",
    "ConstrainedBox",
    "LimitedBox",
    "Gap",
    "VerticalDivider",
    "SingleChildScrollView",
    "Wrap",
    "ButtonBar",
    "Heading",
    "Title",
    "Subtitle",
    "Label",
    "Caption",
    "Link",
    "NetworkImage",
    "AssetImage",
    "CircleImage",
    "Placeholder",
    "SwitchListTile",
    "CheckboxListTile",
    "RadioListTile",
    "ActionChip",
    "ChoiceChip",
    "CircleAvatar",
    "BackButton",
    "CloseButton",
    "MenuButton",
    "SectionHeader",
    "EmptyState",
    "ErrorState",
    "LoadingState",
    "InfoCard",
    "StatCard",
    "SettingsTile",
    "NavigationTile",
    "FormSection",
    # v1.3 — data layer
    "Database",
    "Model",
    "Field",
    "column",
    "Query",
    "Migration",
    "Cache",
    "cached",
    # v1.3 — explicit animation
    "AnimationController",
    "Tween",
    "curve",
    "parse_url",
]
