"""
Pydrud — Build native Android apps with Python.

A lightweight, Flutter-inspired framework that converts a declarative
Python widget tree into native Android Views at runtime. No XML layouts,
no Kotlin UI code — just Python.
"""

__version__ = "1.4.0"
__app_name__ = "Pydrud"

from pydrud.main import App
from pydrud.core.state import State, ReactiveDict
from pydrud.core.store import Store, Selector, Computed, ReactiveList
from pydrud.core.events import Event, EventDispatcher
from pydrud.core.results import Result, ResultError
from pydrud.core.tasks import TaskRunner, Timer, debounce, throttle
from pydrud.core.responsive import Responsive, MediaQuery
from pydrud.navigation import Router, NavigationStack, Route, parse_url
from pydrud.core.controllers import AnimationController, Tween, curve
from pydrud.data import Cache, Database, Field, Migration, Model, Query, cached, column
from pydrud.widgets import (
    Widget,
    Container,
    Column,
    Row,
    Center,
    Spacer,
    Divider,
    Stack,
    Positioned,
    SizedBox,
    Padding,
    Card,
    ListView,
    GridView,
    Text,
    Button,
    TextField,
    Image,
    Icon,
    Checkbox,
    Switch,
    ProgressBar,
    Slider,
    Dropdown,
    Radio,
    AppBar,
    Scaffold,
    FloatingActionButton,
    Style,
    EdgeInsets,
    Alignment,
    FontStyle,
    Border,
    BorderSide,
    BorderRadius,
    Colors,
    Icons,
    Theme,
    Spacing,
    Radius,
    Elevation,
    Motion,
    Tokens,
    ColorScheme,
    Typography,
    ListTile,
    ExpansionTile,
    Chip,
    Badge,
    Avatar,
    Banner,
    Tooltip,
    Tab,
    Tabs,
    NavItem,
    BottomNavigationBar,
    NavigationRail,
    Drawer,
    SegmentedButton,
    SearchBar,
    Rating,
    CircularProgress,
    Skeleton,
    RefreshIndicator,
    Stepper,
    WebView,
    VideoPlayer,
    Chart,
    GestureDetector,
    InkWell,
    Dismissible,
    Draggable,
    Animation,
    AnimatedContainer,
    AnimatedOpacity,
    AnimatedScale,
    AnimatedRotation,
    AnimatedSwitcher,
    FadeIn,
    SlideIn,
    ScaleIn,
    Hero,
    animate,
    Form,
    FormField,
    required,
    min_length,
    max_length,
    email,
    phone,
    url,
    numeric,
    between,
    pattern,
    matches,
    custom,
    Canvas, Paint, Path, radial_point,
    CameraPreview, MapView, Marker, RichText, Span, Markdown,
    ReorderableList, InfiniteList,
)

__all__ = [
    "App",
    "Responsive",
    "MediaQuery",
    "Router",
    "NavigationStack",
    "Route",
    "State",
    "ReactiveDict",
    "Store",
    "Selector",
    "Computed",
    "ReactiveList",
    "Event",
    "EventDispatcher",
    "Result",
    "ResultError",
    "TaskRunner",
    "Timer",
    "debounce",
    "throttle",
    "Widget",
    "Container",
    "Column",
    "Row",
    "Center",
    "Spacer",
    "Divider",
    "Stack",
    "Positioned",
    "SizedBox",
    "Padding",
    "Card",
    "ListView",
    "GridView",
    "Text",
    "Button",
    "TextField",
    "Image",
    "Icon",
    "Checkbox",
    "Switch",
    "ProgressBar",
    "Slider",
    "Dropdown",
    "Radio",
    "AppBar",
    "Scaffold",
    "FloatingActionButton",
    "Style",
    "EdgeInsets",
    "Alignment",
    "FontStyle",
    "Border",
    "BorderSide",
    "BorderRadius",
    "Colors",
    "Spacing",
    "Radius",
    "Elevation",
    "Motion",
    "Tokens",
    "Icons",
    "Theme",
    "ColorScheme",
    "Typography",
    "ListTile",
    "ExpansionTile",
    "Chip",
    "Badge",
    "Avatar",
    "Banner",
    "Tooltip",
    "Tab",
    "Tabs",
    "NavItem",
    "BottomNavigationBar",
    "NavigationRail",
    "Drawer",
    "SegmentedButton",
    "SearchBar",
    "Rating",
    "CircularProgress",
    "Skeleton",
    "RefreshIndicator",
    "Stepper",
    "WebView",
    "VideoPlayer",
    "Chart",
    "GestureDetector",
    "InkWell",
    "Dismissible",
    "Draggable",
    "Animation",
    "AnimatedContainer",
    "AnimatedOpacity",
    "AnimatedScale",
    "AnimatedRotation",
    "AnimatedSwitcher",
    "FadeIn",
    "SlideIn",
    "ScaleIn",
    "Hero",
    "animate",
    "Form",
    "FormField",
    "required",
    "min_length",
    "max_length",
    "email",
    "phone",
    "url",
    "numeric",
    "between",
    "pattern",
    "matches",
    "custom",
    # v1.3 — painting, hardware, maps, rich text and big lists
    "Canvas",
    "Paint",
    "Path",
    "radial_point",
    "CameraPreview",
    "MapView",
    "Marker",
    "RichText",
    "Span",
    "Markdown",
    "ReorderableList",
    "InfiniteList",
    # v1.3 — data layer
    "Database",
    "Model",
    "Field",
    "column",
    "Query",
    "Migration",
    "Cache",
    "cached",
    # v1.3 — explicit animation
    "AnimationController",
    "Tween",
    "curve",
    "parse_url",
]
