"""
``pydrud docs`` — generate a static, offline API reference.

Everything is introspected from the installed package plus your own
``src/`` modules, so the docs can never drift from the code. The output is
a handful of self-contained HTML files; host them anywhere or open
``docs/index.html`` directly.
"""

from __future__ import annotations

import html
import inspect
import os
from typing import Any

_CSS = """
:root { --bg:#0b1020; --panel:#121a33; --ink:#e6e9f5; --muted:#99a2c0;
        --accent:#8b8ff5; --code:#1b2444; }
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--ink);
       font:15px/1.65 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; }
header { padding:28px 40px; border-bottom:1px solid #222c50;
         display:flex; align-items:baseline; gap:16px; }
header h1 { margin:0; font-size:22px; letter-spacing:-0.3px; }
header span { color:var(--muted); font-size:13px; }
.wrap { display:flex; min-height:calc(100vh - 80px); }
nav { width:260px; border-right:1px solid #222c50; padding:24px 0;
      position:sticky; top:0; align-self:flex-start; max-height:100vh;
      overflow:auto; }
nav a { display:block; padding:6px 24px; color:var(--muted);
        text-decoration:none; font-size:14px; }
nav a:hover { color:var(--ink); background:var(--panel); }
main { flex:1; padding:32px 44px; max-width:960px; }
h2 { margin:34px 0 6px; font-size:19px; }
h3 { margin:26px 0 4px; font-size:16px; color:var(--accent); }
.sig { background:var(--code); padding:10px 14px; border-radius:8px;
       font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:13px;
       overflow-x:auto; }
p.doc { color:var(--muted); white-space:pre-wrap; margin:8px 0 0; }
.badge { display:inline-block; font-size:11px; padding:2px 8px;
         border-radius:999px; background:#232e58; color:var(--muted);
         margin-left:8px; }
footer { padding:24px 44px; color:var(--muted); font-size:13px;
         border-top:1px solid #222c50; }
"""


def _signature(obj: Any) -> str:
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return "(...)"


def _doc(obj: Any) -> str:
    return inspect.getdoc(obj) or ""


def _public_members(module) -> list[tuple[str, Any]]:
    names = getattr(module, "__all__", None)
    if names is None:
        names = [n for n in dir(module) if not n.startswith("_")]
    members = []
    for name in names:
        member = getattr(module, name, None)
        if member is None:
            continue
        if inspect.isclass(member) or inspect.isfunction(member):
            if getattr(member, "__module__", "").startswith(
                    module.__name__.split(".")[0]):
                members.append((name, member))
    return sorted(members, key=lambda item: item[0])


def _render_member(name: str, member: Any) -> str:
    out = [f'<h3 id="{html.escape(name)}">{html.escape(name)}'
           f'<span class="badge">'
           f'{"class" if inspect.isclass(member) else "function"}</span></h3>']
    out.append(f'<div class="sig">{html.escape(name + _signature(member))}</div>')
    doc = _doc(member)
    if doc:
        out.append(f'<p class="doc">{html.escape(doc)}</p>')
    if inspect.isclass(member):
        methods = [(n, m) for n, m in inspect.getmembers(member, inspect.isfunction)
                   if not n.startswith("_")]
        for method_name, method in sorted(methods)[:40]:
            out.append(f'<div class="sig">{html.escape(name)}.'
                       f'{html.escape(method_name + _signature(method))}</div>')
            summary = (_doc(method).splitlines() or [""])[0]
            if summary:
                out.append(f'<p class="doc">{html.escape(summary)}</p>')
    return "\n".join(out)


def _page(title: str, nav: str, body: str, version: str) -> str:
    return (f"<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
            f"<meta name='viewport' content='width=device-width,initial-scale=1'>"
            f"<title>{html.escape(title)}</title><style>{_CSS}</style></head>"
            f"<body><header><h1>Pydrud</h1>"
            f"<span>v{version} — Android apps in Python</span></header>"
            f"<div class='wrap'><nav>{nav}</nav><main>{body}</main></div>"
            f"<footer>Generated by <code>pydrud docs</code>. "
            f"Everything here is introspected from the installed package.</footer>"
            f"</body></html>")


def build_docs(project_dir: str = ".", output: str = "docs") -> str:
    """Write the HTML reference and return the output directory."""
    import pydrud

    out_dir = os.path.join(project_dir, output)
    os.makedirs(out_dir, exist_ok=True)
    version = getattr(pydrud, "__version__", "")

    modules = ["pydrud", "pydrud.main", "pydrud.navigation",
               "pydrud.widgets", "pydrud.widgets.canvas",
               "pydrud.widgets.advanced", "pydrud.core.store",
               "pydrud.core.controllers", "pydrud.core.tasks",
               "pydrud.core.results", "pydrud.data.database",
               "pydrud.data.cache", "pydrud.services.native",
               "pydrud.services.http", "pydrud.packages", "pydrud.testing"]

    pages: list[tuple[str, str]] = []
    for name in modules:
        try:
            module = __import__(name, fromlist=["x"])
        except Exception:                                # pragma: no cover
            continue
        members = _public_members(module)
        if not members:
            continue
        body = [f"<h2>{html.escape(name)}</h2>"]
        doc = _doc(module)
        if doc:
            body.append(f'<p class="doc">{html.escape(doc)}</p>')
        body.extend(_render_member(n, m) for n, m in members)
        pages.append((name, "\n".join(body)))

    nav = "\n".join(f'<a href="{name.replace(".", "_")}.html">{name}</a>'
                    for name, _ in pages)
    nav = '<a href="index.html"><strong>Overview</strong></a>' + nav

    for name, body in pages:
        path = os.path.join(out_dir, f"{name.replace('.', '_')}.html")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(_page(name, nav, body, version))

    # Overview page: README if present, otherwise a module index.
    readme = os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(pydrud.__file__))), "README.md")
    overview = ["<h2>Overview</h2>"]
    if os.path.exists(readme):
        text = open(readme, encoding="utf-8").read()[:6000]
        overview.append(f'<p class="doc">{html.escape(text)}</p>')
    else:
        overview.append("<ul>" + "".join(
            f'<li><a href="{n.replace(".", "_")}.html">{n}</a></li>'
            for n, _ in pages) + "</ul>")
    index = os.path.join(out_dir, "index.html")
    with open(index, "w", encoding="utf-8") as handle:
        handle.write(_page("Pydrud API", nav, "\n".join(overview), version))

    return out_dir


def serve_docs(directory: str, port: int = 8000) -> None:        # pragma: no cover
    """Serve the generated docs locally."""
    import functools
    import http.server
    import socketserver

    handler = functools.partial(http.server.SimpleHTTPRequestHandler,
                                directory=directory)
    with socketserver.TCPServer(("0.0.0.0", port), handler) as server:
        print(f"  Serving {directory} on http://localhost:{port} (Ctrl-C to stop)")
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            pass
