"""Read and update the dependency-free ``pydrud.yaml`` project manifest.

Pydrud deliberately keeps its command-line install small, so the generated
project file uses a documented YAML subset rather than requiring PyYAML.  The
subset supports top-level scalars and top-level lists, which covers every
Android setting managed by the project generator.
"""

from __future__ import annotations

import ast
import os
import re
from typing import Iterable


_KEY_VALUE = re.compile(r"^(?P<key>[A-Za-z_][A-Za-z0-9_]*)\s*:\s*(?P<value>.*)$")


def _without_comment(value: str) -> str:
    """Remove an unquoted YAML comment from *value*."""
    quote = ""
    escaped = False
    for index, char in enumerate(value):
        if escaped:
            escaped = False
            continue
        if char == "\\" and quote == '"':
            escaped = True
            continue
        if char in "\"'":
            if not quote:
                quote = char
            elif quote == char:
                quote = ""
            continue
        if char == "#" and not quote and (index == 0 or value[index - 1].isspace()):
            return value[:index].rstrip()
    return value.strip()


def _scalar(value: str) -> str:
    value = _without_comment(value).strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        try:
            parsed = ast.literal_eval(value)
        except (SyntaxError, ValueError):
            return value[1:-1]
        return str(parsed)
    return value


def _inline_list(value: str) -> list[str]:
    body = value.strip()[1:-1].strip()
    if not body:
        return []

    # Python's literal syntax is also valid for the quoted lists generated by
    # Pydrud. Fall back to a small quote-aware splitter for YAML bare words.
    try:
        parsed = ast.literal_eval(value)
    except (SyntaxError, ValueError):
        parsed = None
    if isinstance(parsed, (list, tuple)):
        return [str(item) for item in parsed]

    items: list[str] = []
    quote = ""
    start = 0
    escaped = False
    for index, char in enumerate(body):
        if escaped:
            escaped = False
            continue
        if char == "\\" and quote == '"':
            escaped = True
            continue
        if char in "\"'":
            if not quote:
                quote = char
            elif quote == char:
                quote = ""
        elif char == "," and not quote:
            items.append(_scalar(body[start:index]))
            start = index + 1
    items.append(_scalar(body[start:]))
    return [item for item in items if item]


def load_project_config(project_dir: str) -> dict[str, str | list[str]]:
    """Load top-level scalars and lists from ``pydrud.yaml``.

    Nested mappings are intentionally ignored: Android settings form a flat,
    easy-to-edit system-level manifest. Both ``permissions: [CAMERA]`` and a
    block list are accepted.
    """
    path = os.path.join(project_dir, "pydrud.yaml")
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, encoding="utf-8") as handle:
            lines = handle.readlines()
    except OSError:
        return {}

    result: dict[str, str | list[str]] = {}
    list_key: str | None = None
    for raw in lines:
        line = raw.rstrip("\r\n")
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue

        if line[:1].isspace():
            if list_key and stripped.startswith("-"):
                item = _scalar(stripped[1:].strip())
                if item:
                    current = result.get(list_key)
                    if not isinstance(current, list):
                        current = []
                        result[list_key] = current
                    current.append(item)
            continue

        match = _KEY_VALUE.match(line)
        if not match:
            list_key = None
            continue
        key = match.group("key")
        value = _without_comment(match.group("value")).strip()
        if not value:
            # Keep an empty scalar as an empty string, but remember the key:
            # the first following ``- item`` promotes it to a block list.
            # This makes both ``app_links_host:`` and ``permissions:`` valid.
            result[key] = ""
            list_key = key
        elif value.startswith("[") and value.endswith("]"):
            result[key] = _inline_list(value)
            list_key = None
        else:
            result[key] = _scalar(value)
            list_key = None
    return result


def quote_yaml(value: object) -> str:
    """Return a safe double-quoted scalar for generated YAML."""
    text = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def set_list(project_dir: str, key: str, values: Iterable[str]) -> None:
    """Set a top-level block list while preserving the rest of the file."""
    path = os.path.join(project_dir, "pydrud.yaml")
    if not os.path.isfile(path):
        return
    with open(path, encoding="utf-8") as handle:
        lines = handle.read().splitlines()

    values = list(dict.fromkeys(str(value) for value in values if str(value)))
    replacement = [f"{key}:"] + [f"  - {quote_yaml(value)}" for value in values]
    start: int | None = None
    end: int | None = None
    for index, line in enumerate(lines):
        if line[:1].isspace() or not _KEY_VALUE.match(line):
            continue
        found = _KEY_VALUE.match(line)
        if found and found.group("key") == key:
            start = index
            end = index + 1
            while end < len(lines) and (not lines[end].strip() or lines[end][:1].isspace()):
                end += 1
            break

    if start is None:
        if lines and lines[-1].strip():
            lines.append("")
        lines.extend(replacement)
    else:
        lines[start:end] = replacement
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")


def set_scalar(project_dir: str, key: str, value: object) -> None:
    """Set a top-level scalar while preserving the rest of the file.

    Booleans render as ``true``/``false`` and numbers unquoted; anything
    else is double-quoted with :func:`quote_yaml`. Used by
    ``pydrud init android`` to record platform choices such as
    ``camera:`` without disturbing hand-written comments.
    """
    path = os.path.join(project_dir, "pydrud.yaml")
    if not os.path.isfile(path):
        return
    with open(path, encoding="utf-8") as handle:
        lines = handle.read().splitlines()

    if isinstance(value, bool):
        rendered = "true" if value else "false"
    elif isinstance(value, (int, float)):
        rendered = str(value)
    else:
        rendered = quote_yaml(value)
    replacement = f"{key}: {rendered}"
    for index, line in enumerate(lines):
        if line[:1].isspace():
            continue
        found = _KEY_VALUE.match(line)
        if found and found.group("key") == key:
            lines[index] = replacement
            break
    else:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append(replacement)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
