"""
Shipping to the Play Store: signing keys, icons, splash screens and
manifest permissions.

``pydrud keygen`` creates an upload key and writes ``keystore.properties``
(already in ``.gitignore``); the generated ``app/build.gradle.kts`` picks it
up automatically, so ``pydrud build --release`` produces a *signed* APK or
AAB instead of a debug-signed one.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import xml.etree.ElementTree as ET
from typing import Iterable, Optional

#: Friendly names → the real Android permission constants.
PERMISSIONS = {
    "camera": "CAMERA",
    "microphone": "RECORD_AUDIO",
    "record_audio": "RECORD_AUDIO",
    "location": "ACCESS_FINE_LOCATION",
    "location_coarse": "ACCESS_COARSE_LOCATION",
    "location_background": "ACCESS_BACKGROUND_LOCATION",
    "notifications": "POST_NOTIFICATIONS",
    "vibrate": "VIBRATE",
    "internet": "INTERNET",
    "storage": "READ_MEDIA_IMAGES",
    "storage_video": "READ_MEDIA_VIDEO",
    "storage_audio": "READ_MEDIA_AUDIO",
    "contacts": "READ_CONTACTS",
    "calendar": "READ_CALENDAR",
    "phone": "READ_PHONE_STATE",
    "sms": "RECEIVE_SMS",
    "bluetooth": "BLUETOOTH_CONNECT",
    "bluetooth_scan": "BLUETOOTH_SCAN",
    "nfc": "NFC",
    "biometric": "USE_BIOMETRIC",
    "activity": "ACTIVITY_RECOGNITION",
    "boot": "RECEIVE_BOOT_COMPLETED",
    "foreground_service": "FOREGROUND_SERVICE",
    "wake_lock": "WAKE_LOCK",
}

ANDROID_NS = "http://schemas.android.com/apk/res/android"

#: Launcher icon sizes (density bucket → pixels).
ICON_SIZES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144,
              "xxxhdpi": 192}


def resolve_permission(name: str) -> str:
    """``"camera"`` → ``"CAMERA"``; unknown names pass through upper-cased."""
    key = str(name).strip().lower()
    return PERMISSIONS.get(key, key.upper())


# ──────────────────────────────────────────────────────────────────────────
# Signing
# ──────────────────────────────────────────────────────────────────────────


def create_keystore(project_dir: str, *, alias: str = "release",
                    password: str = "", validity: int = 10000,
                    dname: Optional[str] = None,
                    filename: str = "upload-keystore.jks") -> bool:
    """Generate an upload keystore with ``keytool`` and record its settings.

    Returns True on success. The private key never leaves the project, and
    ``keystore.properties`` is git-ignored by the scaffold.
    """
    keytool = shutil.which("keytool")
    if not keytool:
        print("  [x] keytool not found — install a JDK 17+ and retry.")
        return False
    if len(password) < 6:
        print("  [x] Keystore passwords must be at least 6 characters.")
        return False

    android_dir = os.path.join(project_dir, "android")
    os.makedirs(android_dir, exist_ok=True)
    keystore_path = os.path.join(android_dir, filename)
    if os.path.exists(keystore_path):
        print(f"  [!] {filename} already exists — keeping it "
              f"(delete it first to regenerate).")
        return False

    name = dname or (f"CN={os.path.basename(os.path.abspath(project_dir))}, "
                     f"OU=Pydrud, O=Pydrud, C=US")
    command = [
        keytool, "-genkeypair", "-v",
        "-keystore", keystore_path,
        "-alias", alias,
        "-keyalg", "RSA", "-keysize", "2048",
        "-validity", str(int(validity)),
        "-storepass", password, "-keypass", password,
        "-dname", name,
    ]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        print("  [x] keytool failed:")
        print("      " + (result.stderr.strip().splitlines() or ["unknown"])[-1])
        return False

    properties = os.path.join(android_dir, "keystore.properties")
    with open(properties, "w", encoding="utf-8") as handle:
        handle.write(
            "# Generated by 'pydrud keygen' — NEVER commit this file.\n"
            f"storeFile={filename}\n"
            f"storePassword={password}\n"
            f"keyAlias={alias}\n"
            f"keyPassword={password}\n")
    os.chmod(properties, 0o600)

    print(f"  [ok] Keystore:   android/{filename}")
    print(f"  [ok] Properties: android/keystore.properties (chmod 600)")
    print("\n  Back up both files somewhere safe — losing them means you can "
          "never update\n  this app on Google Play again.")
    print("\n  Next: pydrud build --release --bundle   # signed .aab for Play")
    return True


def signing_status(project_dir: str) -> dict:
    """What ``pydrud build --release`` will actually do."""
    properties = os.path.join(project_dir, "android", "keystore.properties")
    if not os.path.exists(properties):
        return {"configured": False, "reason": "no keystore.properties",
                "signed_with": "debug key"}
    values = {}
    for line in open(properties, encoding="utf-8"):
        if "=" in line and not line.strip().startswith("#"):
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()
    store = os.path.join(project_dir, "android", values.get("storeFile", ""))
    return {"configured": os.path.exists(store),
            "alias": values.get("keyAlias", ""),
            "store": values.get("storeFile", ""),
            "signed_with": "release key" if os.path.exists(store) else "debug key"}


# ──────────────────────────────────────────────────────────────────────────
# Icons and splash
# ──────────────────────────────────────────────────────────────────────────


def generate_icons(project_dir: str, *, source: Optional[str] = None,
                   background: str = "#FF6366F1",
                   splash_text: Optional[str] = None) -> list[str]:
    """Render launcher icons for every density plus a splash drawable.

    With no *source* image, a clean lettermark is generated from the app
    name, so a brand-new project still looks deliberate on the home screen.
    """
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:                                  # pragma: no cover
        print("  [x] Pillow is required: pip install pillow")
        return []

    res_dir = os.path.join(project_dir, "android", "app", "src", "main", "res")
    name = os.path.basename(os.path.abspath(project_dir))
    written: list[str] = []

    if source and os.path.exists(source):
        master = Image.open(source).convert("RGBA")
    else:
        master = _lettermark(name, background)

    for bucket, size in ICON_SIZES.items():
        folder = os.path.join(res_dir, f"mipmap-{bucket}")
        os.makedirs(folder, exist_ok=True)
        icon = master.resize((size, size), Image.LANCZOS)
        path = os.path.join(folder, "ic_launcher.png")
        icon.save(path)
        written.append(path)
        # Round icon: same art, circular mask.
        round_path = os.path.join(folder, "ic_launcher_round.png")
        _circular(icon).save(round_path)
        written.append(round_path)

    # Adaptive icon (API 26+): background colour + foreground art.
    anydpi = os.path.join(res_dir, "mipmap-anydpi-v26")
    os.makedirs(anydpi, exist_ok=True)
    adaptive = os.path.join(anydpi, "ic_launcher.xml")
    with open(adaptive, "w", encoding="utf-8") as handle:
        handle.write(
            '<?xml version="1.0" encoding="utf-8"?>\n'
            '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@color/ic_launcher_background" />\n'
            '    <foreground android:drawable="@mipmap/ic_launcher_foreground" />\n'
            '</adaptive-icon>\n')
    written.append(adaptive)

    for bucket, size in ICON_SIZES.items():
        folder = os.path.join(res_dir, f"mipmap-{bucket}")
        foreground = master.resize((size, size), Image.LANCZOS)
        padded = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        inner = foreground.resize((int(size * 0.66), int(size * 0.66)),
                                  Image.LANCZOS)
        padded.paste(inner, (int(size * 0.17), int(size * 0.17)), inner)
        path = os.path.join(folder, "ic_launcher_foreground.png")
        padded.save(path)
        written.append(path)

    values = os.path.join(res_dir, "values")
    os.makedirs(values, exist_ok=True)
    colors = os.path.join(values, "ic_launcher_background.xml")
    with open(colors, "w", encoding="utf-8") as handle:
        handle.write('<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
                     f'    <color name="ic_launcher_background">'
                     f'{_to_rgb_hex(background)}</color>\n</resources>\n')
    written.append(colors)

    # Splash screen: a layer-list drawable Android shows before the first frame.
    drawable = os.path.join(res_dir, "drawable")
    os.makedirs(drawable, exist_ok=True)
    splash = os.path.join(drawable, "splash.xml")
    with open(splash, "w", encoding="utf-8") as handle:
        handle.write(
            '<?xml version="1.0" encoding="utf-8"?>\n'
            '<layer-list xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <item android:drawable="@color/ic_launcher_background" />\n'
            '    <item android:gravity="center">\n'
            '        <bitmap android:src="@mipmap/ic_launcher" '
            'android:gravity="center" />\n'
            '    </item>\n'
            '</layer-list>\n')
    written.append(splash)

    print(f"  [ok] Launcher icons for {len(ICON_SIZES)} densities")
    print(f"  [ok] Adaptive icon + splash drawable")
    if splash_text:
        print(f"  [i]  Splash text '{splash_text}' — set it in themes.xml")
    return written


def _lettermark(name: str, background: str):
    from PIL import Image, ImageDraw, ImageFont

    size = 512
    image = Image.new("RGBA", (size, size), _rgba(background))
    draw = ImageDraw.Draw(image)
    letters = "".join(part[0] for part in name.replace("_", " ").split()[:2])
    letters = (letters or name[:1] or "P").upper()
    try:
        font = ImageFont.truetype("DejaVuSans-Bold.ttf", 230)
    except OSError:
        font = ImageFont.load_default()
    box = draw.textbbox((0, 0), letters, font=font)
    draw.text(((size - box[2] + box[0]) / 2, (size - box[3] + box[1]) / 2 - 12),
              letters, font=font, fill=(255, 255, 255, 255))
    return image


def _circular(image):
    from PIL import Image, ImageDraw

    mask = Image.new("L", image.size, 0)
    ImageDraw.Draw(mask).ellipse((0, 0) + image.size, fill=255)
    out = image.copy()
    out.putalpha(mask)
    return out


def _rgba(color: str) -> tuple:
    value = color.lstrip("#")
    if len(value) == 8:                     # ARGB
        a, r, g, b = (int(value[i:i + 2], 16) for i in (0, 2, 4, 6))
        return (r, g, b, a)
    if len(value) == 6:
        return tuple(int(value[i:i + 2], 16) for i in (0, 2, 4)) + (255,)
    return (99, 102, 241, 255)


def _to_rgb_hex(color: str) -> str:
    r, g, b, _ = _rgba(color)
    return f"#{r:02X}{g:02X}{b:02X}"


# ──────────────────────────────────────────────────────────────────────────
# Permissions
# ──────────────────────────────────────────────────────────────────────────


def update_permissions(project_dir: str, *, add: Optional[Iterable[str]] = None,
                       remove: Optional[Iterable[str]] = None) -> list[str]:
    """Add or remove ``<uses-permission>`` entries in the manifest."""
    manifest_path = os.path.join(project_dir, "android", "app", "src", "main",
                                 "AndroidManifest.xml")
    if not os.path.exists(manifest_path):
        print("  [x] AndroidManifest.xml not found — run 'pydrud build' once.")
        return []

    ET.register_namespace("android", ANDROID_NS)
    tree = ET.parse(manifest_path)
    root = tree.getroot()
    attribute = f"{{{ANDROID_NS}}}name"
    existing = {node.get(attribute) for node in root.findall("uses-permission")}

    changed: list[str] = []
    for name in add or []:
        full = f"android.permission.{resolve_permission(name)}"
        if full in existing:
            continue
        node = ET.SubElement(root, "uses-permission")
        node.set(attribute, full)
        existing.add(full)
        changed.append(resolve_permission(name))

    for name in remove or []:
        full = f"android.permission.{resolve_permission(name)}"
        for node in root.findall("uses-permission"):
            if node.get(attribute) == full:
                root.remove(node)
                changed.append(resolve_permission(name))

    if changed:
        ET.indent(tree, space="    ")
        tree.write(manifest_path, encoding="utf-8", xml_declaration=True)
    return changed


def list_permissions(project_dir: str) -> list[str]:
    manifest_path = os.path.join(project_dir, "android", "app", "src", "main",
                                 "AndroidManifest.xml")
    if not os.path.exists(manifest_path):
        return []
    tree = ET.parse(manifest_path)
    attribute = f"{{{ANDROID_NS}}}name"
    return sorted(node.get(attribute, "").rsplit(".", 1)[-1]
                  for node in tree.getroot().findall("uses-permission"))
