"""Backward-compatible imports for the starter's reusable components.

New code should import from :mod:`app.components`. This module remains so apps
generated by earlier Pydrud versions can move files gradually.
"""

from app.components import demo_button, page_body, section

__all__ = ["demo_button", "page_body", "section"]
